### ISSUE TITLE
Typesense v0.24.+ Nested fields support

### ISSUE THREAD

**Issue by artvichi** [typesense/firestore-typesense-search#47] opened 2023-03-17 18:33 UTC
## Description

Nested fields support was added to the Typesense v0.24.
Wondering when you're planning to support it in the extension along with updated docs on how to do it?

Thank you, please let me know if you already have something for this and it's a duplicate.

**Comment by jasonbosco** [comment] 2023-03-17 18:45
This is a duplicate of https://github.com/typesense/firestore-typesense-search/issues/43#issuecomment-1459124822. 

You'll find more info in that comment.

**Closed by jasonbosco** 2023-03-17 18:45 UTC
